# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import os
import sys

def main():
    if len(sys.argv) < 3:
        print("Usage: python generate_embedded_schemas.py <repo_root> <output_file>")
        sys.exit(1)
        
    repo_root = sys.argv[1]
    output_file = sys.argv[2]
    
    v08_s2c = os.path.join(repo_root, "specification/v0_8/json/server_to_client.json")
    v09_s2c = os.path.join(repo_root, "specification/v0_9/json/server_to_client.json")
    v09_common = os.path.join(repo_root, "specification/v0_9/json/common_types.json")
    v08_catalog = os.path.join(repo_root, "specification/v0_8/json/standard_catalog_definition.json")
    v09_catalog = os.path.join(repo_root, "specification/v0_9/json/basic_catalog.json")
    
    def read_file(path):
        with open(path, 'r') as f:
            return f.read()
            
    v08_s2c_content = read_file(v08_s2c)
    v09_s2c_content = read_file(v09_s2c)
    v09_common_content = read_file(v09_common)
    v08_catalog_content = read_file(v08_catalog)
    v09_catalog_content = read_file(v09_catalog)
    
    # Ensure output directory exists
    os.makedirs(os.path.dirname(output_file), exist_ok=True)
    
    with open(output_file, 'w') as f:
        f.write('// Generated by generate_embedded_schemas.py. DO NOT EDIT.\n\n')
        f.write('namespace a2ui {\n')
        f.write('namespace internal {\n\n')
        
        f.write('const char* SERVER_TO_CLIENT_SCHEMA_V08 = R"schema(' + v08_s2c_content + ')schema";\n\n')
        f.write('const char* SERVER_TO_CLIENT_SCHEMA_V09 = R"schema(' + v09_s2c_content + ')schema";\n\n')
        f.write('const char* COMMON_TYPES_SCHEMA_V09 = R"schema(' + v09_common_content + ')schema";\n\n')
        f.write('const char* BASIC_CATALOG_V08 = R"schema(' + v08_catalog_content + ')schema";\n\n')
        f.write('const char* BASIC_CATALOG_V09 = R"schema(' + v09_catalog_content + ')schema";\n\n')

        
        f.write('} // namespace internal\n')
        f.write('} // namespace a2ui\n')
    
    print(f"Generated {output_file}")

if __name__ == "__main__":
    main()
