# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: A2UI-agent Python SDK

on:
  push:
    branches:
      - '*'
    paths:
      - 'agent_sdks/python/**'
      - 'specification/**/json/**'
      - 'agent_sdks/conformance/**'
  pull_request:
    paths:
      - 'agent_sdks/python/**'
      - 'specification/**/json/**'
      - 'agent_sdks/conformance/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.x'

      - name: Install `uv` globally
        run: |
          python -m pip install --upgrade pip
          pip install uv

      - name: Check Formatting
        working-directory: agent_sdks/python
        run: uv run pyink --check .

      - name: Check Formatting for Conformance
        working-directory: agent_sdks/conformance
        run: uv run --with pyink pyink --check tests/

      - name: Run unit tests
        working-directory: agent_sdks/python
        run: uv run --with pytest pytest tests/

      - name: Run conformance YAML validation
        working-directory: agent_sdks/conformance
        run: uv run pytest

      - name: Build the python SDK
        working-directory: agent_sdks/python
        run: uv build .

      - name: Run validation scripts on assets packing
        working-directory: agent_sdks/python
        run: uv run python tests/integration/verify_load_real.py
