# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: React renderer

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'renderers/angular/**'
      - 'renderers/flutter/**'
      - 'renderers/lit/**'
      - 'samples/agent/adk/**'
  pull_request:
    paths-ignore:
      - 'renderers/angular/**'
      - 'renderers/flutter/**'
      - 'renderers/lit/**'
      - 'samples/agent/adk/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '22'

      - name: Build web_core dependency
        working-directory: ./renderers/web_core
        run: |
          npm ci
          npm run build

      - name: Build markdown-it dependency
        working-directory: ./renderers/markdown/markdown-it
        run: |
          npm ci
          npm run build

      - name: Install React renderer deps
        working-directory: ./renderers/react
        run: npm ci

      - name: Build React renderer
        working-directory: ./renderers/react
        run: npm run build

      - name: Test React renderer
        working-directory: ./renderers/react
        run: npm test

  build-and-test-demo:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '22'

      - name: Build web_core dependency
        working-directory: ./renderers/web_core
        run: |
          npm ci
          npm run build

      - name: Build markdown-it dependency
        working-directory: ./renderers/markdown/markdown-it
        run: |
          npm ci
          npm run build

      - name: Install React renderer deps
        working-directory: ./renderers/react
        run: npm ci

      - name: Build React Demo
        working-directory: ./renderers/react
        run: npm run build:demo

      - name: Test React Demo
        working-directory: ./renderers/react
        run: npm run test:demo

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '22'

      - name: Build web_core dependency
        working-directory: ./renderers/web_core
        run: |
          npm ci
          npm run build

      - name: Build markdown-it dependency
        working-directory: ./renderers/markdown/markdown-it
        run: |
          npm ci
          npm run build

      - name: Install React renderer deps
        working-directory: ./renderers/react
        run: npm ci

      - name: Build React renderer and its dependencies
        working-directory: ./renderers/react
        run: npm run lint

